dist: trusty
sudo: required
language: erlang
otp_release:
  - 21.3
  - 22.3
  - 23.0
cache:
  directories:
    - plts
    - plts_base
before_install:
  - sudo docker-compose up -d
script:
  - make tests
